### ISSUE TITLE
Cannot Find Module?

### ISSUE THREAD

**Issue by yabdab** [alexanderweiss/nova-prettier#89]
Trying to use a plugin and keep getting this error?

```
[object Object] Error: Cannot find module '@shufo/prettier-plugin-blade'
Require stack:
- /.../node_modules/prettier/index.js
- /.../Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/prettier-service/prettier-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at resolve (node:internal/modules/cjs/helpers:108:19)
    at /.../node_modules/prettier/index.js:39110:25
    at Array.map (<anonymous>)
    at Object.load (/.../node_modules/prettier/index.js:39105:65)
    at Object.load [as loadPlugins] (/.../node_modules/prettier/index.js:15998:27)
    at /Users/mikeyrab/Sites/prettier/node_modules/prettier/index.js:39172:24
    at Object.format (/.../node_modules/prettier/index.js:39188:12)
    at PrettierService.format (/.../Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/prettier-service/prettier-service.js:51:35)
    at async JsonRpcService.processRequest (/.../Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/prettier-service/json-rpc.js:135:19)
```

My .prettierrc.json looks like so...

```
{
  "printWidth": 120,
  "tabWidth": 2,
  "wrapAttributes": "force-expand-multiline",
  "sortTailwindcssClasses": true,
  "bracketSameLine": true,
  "plugins": ["@shufo/prettier-plugin-blade"]
}
```

Using the cli works fine, but not via this extension.

**Comment by yabdab** [comment]
I always find the solution after posting 😆

Use the full path to the plugin(s)
```
"plugins": ["/Users/me/Sites/mysite/node_modules/@shufo/prettier-plugin-blade"]
```
